image: conanio/gcc9

before_script:
  - conan profile new default --detect
  - conan profile update settings.compiler.libcxx=libstdc++11 default
# TODO: It would be cooler to have the conan packages uploaded to a registry on gitlab
  - git clone https://gitlab-ci-token:${CI_JOB_TOKEN}@gitlab.dlr.de/paradigms/parametric.git
  - cd parametric
  - conan create . parametric/0.1@klei_j0/testing -s build_type=Debug
  - cd ..
  - git clone https://gitlab-ci-token:${CI_JOB_TOKEN}@gitlab.dlr.de/paradigms/reflect.git
  - cd reflect
  - conan create . reflect/0.1@klei_j0/testing -s build_type=Debug
  - cd ..

# TODO: debug & release builds for several clang and gcc versions, windows CI

build-debug:
  tags:
    - docker
  stage: build
  script:
    - mkdir build && cd build
    - conan install .. -s build_type=Debug
    - cmake .. -DCMAKE_BUILD_TYPE=Debug -DGRUNK_TESTS=ON
    - make -j
  artifacts:
    paths:
      - build
      # cache:
      #   paths:
      #     - "*.o"

# run tests using the binary built before
test-debug:
  tags:
    - docker
  stage: test
  dependencies:
    - build-debug
  script:
    - cd build
    - conan install .. --generator=virtualrunenv -s build_type=Debug
    - chmod a+x activate_run.sh
    - ./activate_run.sh
    - ./tests/runUnitTests

create-package-debug:
  tags:
    - docker
  stage: deploy
  dependencies:
    - test-debug
  script:
    - conan remote add gitlab ${CI_API_V4_URL}/projects/21487/packages/conan
    - conan create . paradigms/testing -s build_type=Debug
    - CONAN_LOGIN_USERNAME=ci_user CONAN_PASSWORD=${CI_JOB_TOKEN} conan upload grunk/0.1@paradigms/testing --all --remote=gitlab

