# SPDX-FileCopyrightText: 2026 Jan Kleinert <jan.kleinert@dlr.de>
#
# SPDX-License-Identifier: MPL-2.0

[workspace]
name = "grunk"
version = "0.5.0"
authors = ["Jan Kleienrt <jan.kleinert@dlr.de>"]
platforms = ["win-64", "linux-64", "osx-64"]
channels = ["conda-forge"]

[dependencies]
cmake = "*"
ninja = "*"
#TODO: parametric
lua = "*"
sol2 = "*"
taskflow = "*"
yaml-cpp = "*"

[feature.tools]
dependencies = { python = "*" }
pypi-dependencies = { reuse = "*" }

[environments]
"default" = ["default"]
"tools" = ["tools"]

[activation.env]
TF_ENABLE_PROFILER="simple.json"

[tasks]
configure = { cmd = [
    "cmake",
    "-G", "Ninja",
    "-S", ".",
    "-B", "build",
    "-D", "CMAKE_INSTALL_PREFIX=build/install",
    "-D", "CMAKE_BUILD_TYPE={{ config }}",
    "-D", "GRUNK_TESTS=ON",
    "-D", "LUA_INCLUDE_DIR=$CONDA_PREFIX/include"#,
    #"-D", "parametric_DIR=/localdata2/klei_j0/code/parametric/build/install/lib/cmake/parametric/",
], args = [
    { "arg" = "config", "default"="Release"},
]}
build = { cmd = "cmake --build . {{ extra_args }}", cwd = "build", args= [ { "arg" = "extra_args", "default" = "-j"}]}
install = { cmd = "cmake --build . --target install {{ extra_args }}", cwd = "build", args= [ { "arg" = "extra_args", "default" = "-j"}] }
test = { cmd = "./runUnitTests", cwd = "build/tests/cpp" }

_reuse = { cmd = "reuse {{ sub_cmd }}",args = [ { "arg" = "sub_cmd", "default" = "lint"} ] }
[tasks.reuse]
args = [ { "arg" = "sub_cmd", "default" = "lint"} ]
depends-on = [{ task = "_reuse", environment="tools", args = ["{{sub_cmd}}"] }]

[target.linux-64.activation.env]
CMAKE_PREFIX_PATH = "$CONDA_PREFIX"

[target.osx-64.activation.env]
CMAKE_PREFIX_PATH = "$CONDA_PREFIX"

[target.win-64.activation.env]
CMAKE_PREFIX_PATH = "%CONDA_PREFIX%/Library"