# SPDX-FileCopyrightText: 2026 Jan Kleinert <jan.kleinert@dlr.de>
#
# SPDX-License-Identifier: MPL-2.0

name: "Build and test grunk"

on: 

  workflow_call:

    secrets:
      GH_TOKEN:
        description: 'A Github PAT'
        required: false
      CODECOV_TOKEN:
        description: 'Needed to upload coverage report to codecov'
        required: false

    inputs:

      os:
        description: "Operating system to run the job on"
        required: true
        type: string

      config:
        description: "Build configuration (Debug or Release)"
        required: true
        type: string


jobs:

  build:
    runs-on: ${{ inputs.os }}
    steps:
      # checkout, setup pixi, compilers and ccache/sccache
      - uses: actions/checkout@v7
      - name: Set up Visual Studio shell
        if: startsWith(inputs.os, 'windows')
        uses: egor-tensin/vs-shell@v2
        with:
          arch: x64
      - name: Setup ccache
        uses: hendrikmuhs/ccache-action@v1
        if: startsWith(inputs.os, 'windows') == false
        with:
          key: compiler-cache-${{ inputs.os }}-${{ inputs.config }}-${{ inputs.pixienv }}
      - name: Setup sccache
        if: startsWith(inputs.os, 'windows')
        uses: mozilla-actions/sccache-action@v0.0.11

      - name: Setup pixi
        uses: prefix-dev/setup-pixi@v0.10.2
        with:
          cache: true
          cache-write: ${{ github.event_name == 'push' && github.ref_name == 'main' }}
          activate-environment: true

      # configure, build and install grunk
      - name: Configure grunk (Linux, MacOS)
        run: pixi run configure ${{ inputs.config }}
        if: startsWith(inputs.os, 'windows') == false
        env:
          CMAKE_CXX_COMPILER_LAUNCHER: ccache
      - name: Configure grunk (Windows)
        run: pixi run configure ${{ inputs.config }}
        if: startsWith(inputs.os, 'windows')
        env:
          CMAKE_CXX_COMPILER_LAUNCHER: sccache
          SCCACHE_GHA_ENABLED: "true"
      - name: Build and install grunk
        run: pixi run install_cpp -j4

      # save build artifacts

      - name: Create build archive
        run: tar -czf build.tar.gz build
      - name: Upload build archive
        uses: actions/upload-artifact@v7
        with:
          name: build-${{ inputs.os }}-${{ inputs.config }}
          path: build.tar.gz
          retention-days: 1

  test:
    runs-on: ${{ inputs.os }}
    needs: build
    steps:
      - uses: actions/checkout@v7
      - name: Download build directory
        uses: actions/download-artifact@v8
        with:
          name: build-${{ inputs.os }}-${{ inputs.config }}
      - name: Extract build archive
        run: tar -xzf build.tar.gz
      - name: Setup pixi
        uses: prefix-dev/setup-pixi@v0.10.2
        with:
          cache: true
          cache-write: ${{ github.event_name == 'push' && github.ref_name == 'main' }}

      - name: Run unit tests
        run: pixi run test_cpp

  python:
    runs-on: ${{ inputs.os }}
    steps:
      - uses: actions/checkout@v7
      - name: Setup pixi
        uses: prefix-dev/setup-pixi@v0.10.2
        with:
          cache: true
          cache-write: ${{ github.event_name == 'push' && github.ref_name == 'main' }}
          activate-environment: true
      - name: Install python bindings of grunk
        run: pixi run install_python
      - name: Run python tests
        run: pixi run test_python  